
export const CREATE_CLIENT = 'CREATE_CLIENT'
export const FETCH_CLIENTS = 'FETCH_CLIENTS'
export const FETCH_CLIENT = 'FETCH_CLIENT'
export const SEND_CLIENT = 'SEND_CLIENT'
export const LOAD_CLIENTS = 'LOAD_CLIENTS'
export const SELECT_CLIENT = 'SELECT_CLIENT'
export const SAVE_CLIENT = 'SAVE_CLIENT'
